version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - arelle_service
    networks:
      - app-network

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules # don't do it build them in container 
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  arelle_service:
    build: ./arelle_service
    ports:
      - "8001:8000"  # Expose on a different host port if needed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
