apiVersion: v1
kind: Service
metadata:
  name: xbrl-arelle-service
  labels:
    app: xbrl-arelle
spec:
  selector:
    app: xbrl-arelle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP