apiVersion: apps/v1
kind: Deployment
metadata:
  name: xbrl-arelle-deployment
  labels:
    app: xbrl-arelle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xbrl-arelle
  template:
    metadata:
      labels:
        app: xbrl-arelle
    spec:
      containers:
      - name: xbrl-arelle
        image: ghcr.io/open-earth-foundation/xbrl-disclosure-explorer-arelleservice:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8001