apiVersion: apps/v1
kind: Deployment
metadata:
  name: xbrl-backend-deployment
  labels:
    app: xbrl-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xbrl-backend
  template:
    metadata:
      labels:
        app: xbrl-backend
    spec:
      containers:
      - name: xbrl-backend
        image: ghcr.io/open-earth-foundation/xbrl-disclosure-explorer-backend:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: OPENAI_API_KEY
          value: ADD_KEY_HERE
        - name: ASSISTANT_ID
          value: ADD_ID_HERE
        - name: ARELLE_URL
          value: http://xbrl-arelle-service
        - name: CORS_ORIGINS
          value: https://xbrl-explorer.openearth.org
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app/converted_files
          name: backend-storage
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: xbrl-backend-storage