apiVersion: apps/v1
kind: Deployment
metadata:
  name: xbrl-frontend-deployment
  labels:
    app: xbrl-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xbrl-frontend
  template:
    metadata:
      labels:
        app: xbrl-frontend
    spec:
      containers:
      - name: xbrl-frontend
        image: ghcr.io/open-earth-foundation/xbrl-disclosure-explorer-frontend:latest
        imagePullPolicy: Always
        env:
        - name: VITE_BACKEND_URL
          value: http://xbrl-backend-service
        - name: BACKEND_WS_ORIGIN
          value: wss://xbrl-backend-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5173