name: Arelle Service Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'arelle_service/**'
      - '.github/workflows/arelle_service.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      REPOSITORY: open-earth-foundation/xbrl-disclosure-explorer-arelleservice

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Git commit hash
        id: vars
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:arelle_service"
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ steps.vars.outputs.commit_hash }}
