name: Push Tagged Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      PREFIX: open-earth-foundation/xbrl-disclosure-employment
      TAG: ${{ github.ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Git commit hash
        id: vars
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PREFIX }}-frontend:${{ steps.vars.outputs.commit_hash }}
            ${{ env.REGISTRY }}/${{ env.PREFIX }}-frontend:${{ env.TAG }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PREFIX }}-backend:${{ steps.vars.outputs.commit_hash }}
            ${{ env.REGISTRY }}/${{ env.PREFIX }}-backend:${{ env.TAG }}

      - name: Build and push arelleservice image
        uses: docker/build-push-action@v2
        with:
          context: ./arelle_service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PREFIX }}-arelleservice:${{ steps.vars.outputs.commit_hash }}
            ${{ env.REGISTRY }}/${{ env.PREFIX }}-arelleservice:${{ env.TAG }}
